"""Align database indexes with models

Revision ID: 8d4b0c794e96
Revises: 63d529edcf13
Create Date: 2026-07-23 13:19:15.083658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4b0c794e96'
down_revision: Union[str, Sequence[str], None] = '63d529edcf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_attachments_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_task_id'), table_name='task_attachments')
    op.drop_index(op.f('ix_task_attachments_user_id'), table_name='task_attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_attachments_user_id'), 'task_attachments', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_task_id'), 'task_attachments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_attachments_id'), 'task_attachments', ['id'], unique=False)
    # ### end Alembic commands ###
